### ISSUE TITLE
Throws `TypeError: Cannot read property 'indexOf' of null` when use `null` in CDATA ($)

### ISSUE THREAD

**Issue by enkot** [oozcitak/xmlbuilder2#78]
**Describe the bug**
Throws `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of null` when use `null` in CDATA ($)

**To Reproduce**
```js
const doc = { 
  title: {
    $: null,
  },
  description: 'Test description'
}
```

**Expected behavior**
Don't throw exception but skip title field (or show empty tag) in xml, just as if `null` was assigned to `title` directly: 
```js
const doc = { 
  title: null,
  description: 'Test description'
}
```

**Version:**
 - node.js: [12.18.1]
 - xmlbuilder2 [2.4.0]

**Comment by oozcitak** [comment]
I can't replicate your issue. I added a test case but it seems to work as expected.

**Comment by oozcitak** [comment]
@enkot Can you post the complete code?

**Comment by DanielHabenicht** [comment]
I've got the same error. Here is my reproduction: 

```typescript
import { convert } from "xmlbuilder2";

const xmlBase = {
  xliff: {
    "@version": "1.2",
    file: {
      "@datatype": "plaintext",
      "@source-language": "en",
      body: {},
    },
  },
};

xmlBase.xliff.file.body["trans-unit"] = {
  "@id": "test",
  source: {
    $: undefined,
  },
  target: {
    "@state": "translated",
    $: undefined,
  },
};
const test = convert(xmlBase, { prettyPrint: true });
```

Error: 
```bash
TypeError: Cannot read property 'indexOf' of undefined
    at XMLDocumentImpl.createCDATASection (C:\Develop\reproduction\node_modules\@oozcitak\dom\src\dom\DocumentImpl.ts:264:14)
    at XMLBuilderImpl.dat (C:\Develop\reproduction\node_modules\xmlbuilder2\src\builder\XMLBuilderImpl.ts:384:29)
    at XMLBuilderImpl.<anonymous> (C:\Develop\reproduction\node_modules\xmlbuilder2\src\builder\XMLBuilderImpl.ts:130:30)
    at Object.forEachObject (C:\Develop\reproduction\node_modules\@oozcitak\util\src\index.ts:84:18)
    at XMLBuilderImpl.ele (C:\Develop\reproduction\node_modules\xmlbuilder2\src\builder\XMLBuilderImpl.ts:104:7)
    at XMLBuilderImpl.<anonymous> (C:\Develop\reproduction\node_modules\xmlbuilder2\src\builder\XMLBuilderImpl.ts:170:21)
    at Object.forEachObject (C:\Develop\reproduction\node_modules\@oozcitak\util\src\index.ts:84:18)
    at XMLBuilderImpl.ele (C:\Develop\reproduction\node_modules\xmlbuilder2\src\builder\XMLBuilderImpl.ts:104:7)
    at XMLBuilderImpl.<anonymous> (C:\Develop\reproduction\node_modules\xmlbuilder2\src\builder\XMLBuilderImpl.ts:170:21)
    at Object.forEachObject (C:\Develop\reproduction\node_modules\@oozcitak\util\src\index.ts:84:18)
api/v1/node_modules/source-map-support/source-map-support.js:468
Process exited with code 1

```

Version 2.1.2

**Comment by DanielHabenicht** [comment]
After I upgraded to 2.4.1 everything works so I think you can close it. :)
